### ISSUE TITLE
Metodos asignados comentados y completados a espera de revision

### ISSUE THREAD

**Issue by avitoriacdaw1** [jveramdaw1/AgendaContactos#14]
He hecho los tres métodos asignados. Les he puesto un cometario con mi nombre porque estaba venga a olvidar cuales eran los míos. Aún no han sido probados, están a la espera de revisión.

**Comment by jveramdaw1** [comment]
Los acabo de revisar y al parecer creo que están bien aun debo esperar a que diana acabe su parte para poder saber si ningún método da error. Los comentarios están muy bien .
