### ISSUE TITLE
Asignación  de tareas para cada integrante del grupo del proyecto

### ISSUE THREAD

**Issue by jveramdaw1** [jveramdaw1/AgendaContactos#2]
Adrián 
> - Clase contactoPersonal 
 Metodos de la clase Agenda contactos
> -Void añadirContacto()
> -List<Personal> personalesEnLetra(Charles letra)
> -List<Personal> personalesOrdenadosPorFechaNacimiento(Charles letra)
 
Diana
> - Clase ContactoProfesional
> - Clase agendaIo
Metodos de la Clase AgendaContactos
> - contactosEnLetra()
> - totalContactos()
> - list<Contacto> buscarContactos(String texto)

John
> - Clase Contacto
Metodos de la Clase AgendaContactos
> - String toString()
> - List<Personal> felicitar
> - personalesPorRelacion

Si tienen algún inconveniente o no están de acuerdo en la forma del reparto no duden en decirlo.

**Comment by avitoriacdaw1** [comment]
Asumo que "Charles" querías decir "Char". Por lo demás, ok. ¿Cuando se debería empezar a hacerlo?

**Comment by jveramdaw1** [comment]
Huy mi error,  puedes empezar desde hoy ya subí las fechas limites para cada parte.
