### ISSUE TITLE
Fechas límites de entrega 

### ISSUE THREAD

**Issue by jveramdaw1** [jveramdaw1/AgendaContactos#3]
Para las clases Contacto,ContactoProfesional,ContactoPersonal y Agenda Io 
Deben de estar listas para el día 5 de abril
6 y 7 de abril revisaremos estas clases para corregir errores y hacer mejoras(si es necesario)  
Los metodos de la Clase Agenda contactos deben estar listos para el 14 de abril
15 y 16 de abril revisaremos, coerregiremos errores o mejoraremos los metodos (si es necesario)

Estas son las fechas tope para que estén todo listo. Los días que revisaremos el código preferiblemente que sea en grupo vía discord para aportar mejoras o corregir alguna que otra cosa.

**Comment by avitoriacdaw1** [comment]
De acuerdo
