### ISSUE TITLE
Clase Personal cambiado acorde a la revisión

### ISSUE THREAD

**Issue by avitoriacdaw1** [jveramdaw1/AgendaContactos#8]
Puesto comentarios y actualizado constructor.

**Comment by jveramdaw1** [comment]
Acabo de revisar la clase todo esta bien excepto que los comentarios no están claros como para hacer la documentación del  proyecto , tienes d ejemplo los comentarios de la clase Contacto después lo demás esta super bien.
Sigue así  😊😉!!
