### ISSUE TITLE
Clase Profesional modificada acorde a la revision

### ISSUE THREAD

**Issue by dperaltajdaw1** [jveramdaw1/AgendaContactos#9]

**Comment by jveramdaw1** [comment]
En primer lugar no veo comentarios, segundo la super clase esta mal inicializada, para Capitalizar el nombre de la empresa es mejor que uses un método privado, el atributo mensaje debe llamarse firma, tambien debes incorporar el método abstracto getFriamaEmail en este caso para mejorar el código de este método podrías hacer un ArrayList o Array y returnar un valor aleatorio de la lista.
Por lo demás todo esta bien.
Espero la clase AgendaIo máximo hasta hoy y  los demás cambios a mas tardar mañana plis.
Si tienes alguna dificultad o duda pregunta sin temor.
😊😉
